# Generated by Django 6.0.7 on 2026-07-15 18:38

import contratos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255, unique=True)),
                ('nit', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(db_index=True, max_length=100, unique=True)),
                ('modalidad', models.CharField(choices=[('EV', 'Evento'), ('CAP', 'Capitación'), ('PGP', 'Paquete de Gestión Global (PGP)')], default='EV', max_length=3)),
                ('objeto', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3)),
                ('administradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.administradora')),
            ],
        ),
        migrations.CreateModel(
            name='AnexoTarifario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anexo', models.CharField(max_length=255)),
                ('archivo_excel', models.FileField(upload_to=contratos.models.anexo_upload_path)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_previos', models.PositiveIntegerField(default=90, help_text='Días previos para generar la alerta antes del vencimiento.')),
                ('activa', models.BooleanField(default=True)),
                ('ultima_notificacion_enviada', models.DateField(blank=True, null=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerta', to='contratos.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cups', models.CharField(db_index=True, max_length=20)),
                ('descripcion', models.CharField(max_length=500)),
                ('tipo_tecnologia', models.CharField(choices=[('P', 'Procedimiento'), ('M', 'Medicamento'), ('I', 'Insumo')], max_length=1)),
                ('esta_incluido', models.BooleanField(default=True)),
                ('manual_referencia', models.CharField(max_length=50)),
                ('tarifa_base', models.DecimalField(decimal_places=2, max_digits=14)),
                ('porcentaje_pactado', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('valor_final', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('anexo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contratos.anexotarifario')),
            ],
            options={
                'unique_together': {('anexo_origen', 'codigo_cups')},
            },
        ),
    ]
