# Generated by Django 6.0.7 on 2026-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="administradora",
            name="regimen",
            field=models.CharField(
                choices=[
                    ("SUB", "Subsidiado"),
                    ("CON", "Contributivo"),
                    ("AMB", "Ambos"),
                    ("OTR", "Otro"),
                ],
                default="OTR",
                help_text="Régimen que administra la EAPB/EPS.",
                max_length=3,
            ),
        ),
    ]
