# Generated by Django 6.0.7 on 2026-07-16 16:22

import contratos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0002_administradora_regimen"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="administradora",
            options={"ordering": ["nombre"]},
        ),
        migrations.AlterModelOptions(
            name="contrato",
            options={"ordering": ["-fecha_inicio"]},
        ),
        migrations.AddField(
            model_name="administradora",
            name="ciudad",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="administradora",
            name="codigo_postal",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="administradora",
            name="correo",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="administradora",
            name="departamento",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="contrato",
            name="documento_negociacion",
            field=models.FileField(
                blank=True,
                help_text="PDF de la negociación del contrato.",
                null=True,
                upload_to=contratos.models.negociacion_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="administradora",
            name="regimen",
            field=models.CharField(
                choices=[
                    ("SUB", "Subsidiado"),
                    ("CON", "Contributivo"),
                    ("AMB", "Ambos"),
                    ("OTR", "Otro"),
                ],
                default="OTR",
                help_text="Régimen que administra la EAPB/EPS (un mismo NIT puede manejar ambos).",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="objeto",
            field=models.TextField(blank=True),
        ),
    ]
