# Generated by Django 6.0.7 on 2026-07-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contratos",
            "0003_alter_administradora_options_alter_contrato_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detalletarifa",
            options={"ordering": ["hoja", "codigo_cups"]},
        ),
        migrations.AlterUniqueTogether(
            name="detalletarifa",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="detalletarifa",
            name="hoja",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Hoja del Excel de la que provino la fila.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="detalletarifa",
            name="codigo_cups",
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="detalletarifa",
            name="descripcion",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="detalletarifa",
            name="manual_referencia",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="detalletarifa",
            name="porcentaje_pactado",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="detalletarifa",
            name="tarifa_base",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name="detalletarifa",
            name="tipo_tecnologia",
            field=models.CharField(
                choices=[("P", "Procedimiento"), ("M", "Medicamento"), ("I", "Insumo")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="detalletarifa",
            name="valor_final",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=16
            ),
        ),
    ]
