# Generated by Django 6.0.7 on 2026-07-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0004_alter_detalletarifa_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="manual_referencia",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Manual tarifario base, p. ej. ISS 2001, SOAT, Propio.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="porcentaje_negociado",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje pactado sobre el manual (p. ej. 35.00 para +35%).",
                max_digits=6,
            ),
        ),
    ]
