# Generated by Django 6.0.7 on 2026-07-16 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0005_contrato_manual_referencia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveIntegerField()),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        help_text="1 = enero … 12 = diciembre."
                    ),
                ),
                (
                    "poblacion",
                    models.PositiveIntegerField(
                        default=0, help_text="Afiliados cubiertos en el mes."
                    ),
                ),
                (
                    "valor_global",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Techo presupuestal del mes (valor global del PGP).",
                        max_digits=18,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, default="")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_tecnicas",
                        to="contratos.contrato",
                    ),
                ),
            ],
            options={
                "ordering": ["-anio", "-mes"],
                "unique_together": {("contrato", "anio", "mes")},
            },
        ),
        migrations.CreateModel(
            name="LineaNotaTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(db_index=True, max_length=60)),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "frecuencia_esperada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "nota_tecnica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="contratos.notatecnica",
                    ),
                ),
            ],
            options={
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="RegistroConsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(db_index=True)),
                (
                    "codigo",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=60
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=1, max_digits=14),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumos",
                        to="contratos.contrato",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha"],
            },
        ),
    ]
